### ISSUE TITLE
Custom Typeface not working

### ISSUE THREAD

**Issue by krishansharma91** [hanks-zyh/HTextView#11]
I could not find a way to use a custom typeface.

**Comment by Jayvd** [comment]
@krishansharma91 me too, have you found a way?

**Comment by krishansharma91** [comment]
No, had to drop the idea to use it.

**Comment by hanks-zyh** [comment]
sorry,the library dont support it yet

**Comment by MathiasBerwig** [comment]
@krishansharma91, @Jayvd check out the new version: 0.1.4 does support custom typefaces.
