### ISSUE TITLE
Failed to resolve in gradle 9.0 and java 17

### ISSUE THREAD

**Issue by dokju** [hanks-zyh/HTextView#121]
Hello!

I have primarily developed with Swift, and am now studying Android development with Kotlin for the first time.

I had no problem using LTMorphingLabel in Swift and wanted to use htextview in Android, but I am encountering a "Failed to resolve" error.

I've created a sample project and posted the issue, could you possibly take a look?

Thanks!!

https://github.com/YIMSUHWAN/SampleHTextViewAndroid/issues/1

**Comment by Chu-Dream** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
