### ISSUE TITLE
gravity="start" isn't working

### ISSUE THREAD

**Issue by ndvalkov** [hanks-zyh/HTextView#16]
I can't align the text inside the animated View to the left. It aligns top. I don't know if it's supposed to work only with gravity "center", because "start" messes with the animation of the characters somehow.

**Comment by hanks-zyh** [comment]
@ndvalkov I am sorry to tell you that HTextView is not support `gravity="start"`

**Comment by ndvalkov** [comment]
OK, np, very nice library anyways.:)

**Comment by hanks-zyh** [comment]
try last release version https://github.com/hanks-zyh/HTextView/commit/15ccfa93388e935e3f24ffe3cbadc7330427e6b6
