### ISSUE TITLE
How set text color and background in pixelate type?

### ISSUE THREAD

**Issue by Nominalista** [hanks-zyh/HTextView#17]
<com.hanks.htextview.HTextView
        android:id="@+id/title_htv"
        android:layout_width="match_parent"
        android:layout_height="100dp"
        android:layout_centerInParent="true"
        android:gravity="center"
        android:background="@color/primary"
        android:textColor="#FFFFFF"
        android:textSize="30sp"
        htext:animateType="pixelate"
        />

This part gives white background and black text

**Comment by Nominalista** [comment]
Any help?

**Comment by softrice** [comment]
its a bug.
PixelateText should extends HText?
