### ISSUE TITLE
不能显示多行数据？

### ISSUE THREAD

**Issue by sharpdeep** [hanks-zyh/HTextView#19]
`hTextView.animateText("line1 \n line2 \n line3");`不能显示为三行，而是显示成一行？如果想显示多行数据应该怎么办？

**Comment by hanks-zyh** [comment]
@sharpdeep 非常抱歉，因为暂时没有多行的动画，所以不支持多行

**Comment by newtonker** [comment]
@sharpdeep 多行显示的效果你后来是怎么解决的？有什么思路吗？

**Comment by HenryChao24** [comment]
试试 LayoutAnimation呢,博主. 
很棒的库,希望早日加上多行动画.

**Comment by hanks-zyh** [comment]
https://github.com/hanks-zyh/HTextView/commit/15ccfa93388e935e3f24ffe3cbadc7330427e6b6
