### ISSUE TITLE
Update maven repository

### ISSUE THREAD

**Issue by MathiasBerwig** [hanks-zyh/HTextView#23]
Can you please update the maven repository with new code changes (#22)?

**Comment by hanks-zyh** [comment]
@MathiasBerwig updated

**Comment by MathiasBerwig** [comment]
Thank you. I think now you can close #11 and #21. 

My Android Studio can't resolve `compile 'hanks.xyz:htextview-library:0.1.4'`, just with the `@aar` suffix. You just uploaded the `aar` file, right? Maybe we can add this info to the readme, so it will be easier to people use the lib.

**Comment by xtonousou** [comment]
Hello,
my Android Studio can't resolve `compile 'hanks.xyz:htextview-library:0.1.4'`. I want to use `htext:fontAsset` and I can't. Please fix this.

**Comment by MathiasBerwig** [comment]
@xtonousou try `compile 'hanks.xyz:htextview-library:0.1.4@aar'`

**Comment by xtonousou** [comment]
@MathiasBerwig works like a charm! Thank you.
