### ISSUE TITLE
WrapContent not work.

### ISSUE THREAD

**Issue by Huynhvantoan** [hanks-zyh/HTextView#24]
Match_Parent Htextview ok but WrapContent it show wrong.

**Comment by dengcb** [comment]
in my case, 1 digit to 2 digits number will cut, even using match_parent.
I use fall animator.

**Comment by hanks-zyh** [comment]
sorry， the library not support wrap_content up to now

**Comment by dengcb** [comment]
I mean I used match_parent, but when number from 1 digit to 2 digits, like 9 -> 12, the 1 is cut.

**Comment by danlyalex** [comment]
有什么好的方法可以在使用wrapcontent的时候保证字不飞出去屏幕吗

**Comment by hanks-zyh** [comment]
fixed: https://github.com/hanks-zyh/HTextView/commit/15ccfa93388e935e3f24ffe3cbadc7330427e6b6
