### ISSUE TITLE
drawableLeft or others failed

### ISSUE THREAD

**Issue by dengcb** [hanks-zyh/HTextView#25]
Of course I can change my drawableLeft to one imageview + one htextview, but I think it's a bug.

**Comment by hanks-zyh** [comment]
source in here : https://github.com/hanks-zyh/HTextView/blob/master/htextview-library/src/main/java/com/hanks/htextview/HTextView.java#L111

HTextview extends `TextView `, but not super.onDraw(draw) , so it don't support textview  most  attr

**Comment by hanks-zyh** [comment]
try new version https://github.com/hanks-zyh/HTextView/commit/15ccfa93388e935e3f24ffe3cbadc7330427e6b6
