### ISSUE TITLE
two HTextView animate at the same time

### ISSUE THREAD

**Issue by dengcb** [hanks-zyh/HTextView#26]
the first work fine, and the second disappear.

**Comment by dengcb** [comment]
Sorry, the first I use 'match_parent' width, and second 'wrap_content'.
I change the second and two work fine.

**Comment by mohtamohit** [comment]
Can we use HTextView to animate a string more than one line?

**Comment by hanks-zyh** [comment]
@mohtamohit  try this :https://github.com/hanks-zyh/HTextView/commit/15ccfa93388e935e3f24ffe3cbadc7330427e6b6
