### ISSUE TITLE
LineText 边框未闭合

### ISSUE THREAD

**Issue by DaVinci42** [hanks-zyh/HTextView#3]
高分辨屏下边框四角未闭合，尝试把边框线条加粗，会更明显；

canvas.drawLine() 方法绘制水平线，给定的 startY 和 endY 都实际是线条的中心线上的点，所以有半个线宽的差别；

可以把线条长度定为 原长度 + lineWidth / 2 解决

**Comment by hanks-zyh** [comment]
@DaVinci42  感谢，已修改
