### ISSUE TITLE
Changing text color

### ISSUE THREAD

**Issue by RJFares** [hanks-zyh/HTextView#30]
Text color is not dynamic, the value set in xml stays the same.
For example, if programmatically i decide to change text color, it doesn't work.
I tried with .setTextColor() and with SpannableString ForegroundColorSpan method.

**Comment by hanks-zyh** [comment]
fixed in lasted commit @RJFares

**Comment by vedo1608** [comment]
still not working

**Comment by RJFares** [comment]
as of 0.1.5 it's not working.
xml:
animateType="scale"

java:
txt.setTextColor(colorRed); //doesn't change color programmatically

**Comment by theoyuncu8** [comment]
not working

**Comment by theoyuncu8** [comment]
@hanks-zyh  setTextColor(colorRed); // not working

**Comment by Chu-Dream** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
