### ISSUE TITLE
The following classes could not be instantiated

### ISSUE THREAD

**Issue by devious33** [hanks-zyh/HTextView#31]
![image](https://cloud.githubusercontent.com/assets/21035935/17661689/4eaa46da-6313-11e6-8444-eb863a561ec3.png)
Hello, I'm getting this rendering problem after placing this in my layout.xml
` <com.hanks.htextview.HTextView
        android:id="@+id/text"
        android:layout_width="match_parent"
        android:layout_height="100dp"
        android:background="#000000"
        android:gravity="center"
        android:textColor="#FFFFFF"
        android:textSize="30sp"
        htext:animateType="anvil"
        htext:fontAsset="fonts/font-name.ttf" />
 `
 Is there any known solutions for it? thanks in advance

**Comment by hanks-zyh** [comment]
use View.isInEditMode() solved
