### ISSUE TITLE
Changing text color with animation "scale" (reference #30)

### ISSUE THREAD

**Issue by RJFares** [hanks-zyh/HTextView#39]
Text color is not dynamic, the value set in xml stays the same.
For example, if programmatically i decide to change text color, it doesn't work.
I tried with .setTextColor() and with SpannableString ForegroundColorSpan method.

as of 0.1.5 it's not working.
xml:
animateType="scale"

java:
txt.setTextColor(colorRed); //doesn't change color programmatically

**Comment by PGMacDesign** [comment]
I just put in a pull request for this to be fixed here: https://github.com/hanks-zyh/HTextView/pull/47 

This will allow users to set the text color for animations like Scale. 

I disabled the ability to set the text color on rainbow text as that could mess up paint schemes. 

Also, here is a visual of the code in action if anyone needs to see it:
http://i.imgur.com/DJKWRSC.gifv
