### ISSUE TITLE
Urgent issues with the readme!

### ISSUE THREAD

**Issue by MissAbbie** [hanks-zyh/HTextView#4]
There is an urgent issue with the readme in this repo.

A lot of people suffer from epilepsy and seizures from seeing unexpected moving images quickly, which the readme has a lot of. I'm a representative from Social Justice Code (http://socialjusticecode.org) and we suggest adding a trigger warning to the beginning of the readme, warning users before they scroll down. In addition the content has a few issues, including using cis-terms like "boy" as well as age-ist terms like "old" which may turn away or scare younger viewers, or ones who do not identify as boys. We suggest using a neutral term like "they," or if an oppressed person asks for their pronoun to be included, to generate a new image for them and put it on the site.

Thank you for your attention to this matter and helping make Github a better place for all people (✿ -‿-)

**Comment by faizaanceg** [comment]
@MissAbbie  Err..the text in the GIFs is a quote attributed to Steve Jobs

> Older people sit down and ask, 'What is it?' but the boy asks, 'What can I do with it?'.

http://www.brainyquote.com/quotes/quotes/s/stevejobs416883.html#28eqjpO5jQiZ35ew.99

You can be PC with a quote, can you?

**Comment by MissAbbie** [comment]
Steve Jobs was a privileged white cis male. To practically be causing seizures using his quotes is basically adding insult to injury. Literally.

**Comment by faizaanceg** [comment]
Get lost, troll.
