### ISSUE TITLE
SetText doenst work for me

### ISSUE THREAD

**Issue by AviadKlein10** [hanks-zyh/HTextView#43]
and the animation as well.
I've done everything you wrote

what to do??
ty

**Comment by AviadKlein10** [comment]
Oops! Just figured out I need to write 'animateText' and not 'setText'.
Thank you for this great library

**Comment by hanks-zyh** [comment]
try this : https://github.com/hanks-zyh/HTextView/commit/15ccfa93388e935e3f24ffe3cbadc7330427e6b6

**Comment by AviadKlein10** [comment]
Thank you very much! I already figuerd it
Great library thanks!

בתאריך 7 באפר' 2017 05:11,‏ "hanks" <notifications@github.com> כתב:
