### ISSUE TITLE
Doesn't work for strings that demand more than one line on screen? 

### ISSUE THREAD

**Issue by mohtamohit** [hanks-zyh/HTextView#46]
The content flows out of the Screen in case we try to get a string that demands more than one line to be displayed. How to fix?

**Comment by Shuffler** [comment]
@hanks-zyh Any possible fix for multiline text?!

**Comment by lbarrosop** [comment]
@hanks-zyh same problem

**Comment by hanks-zyh** [comment]
`0.1.2` support multiline for some type

**Comment by theapache64** [comment]
@hanks-zyh Does it support multiline for "Scale" type ?
