### ISSUE TITLE
Error inflating class com.hanks.htextview.HTextView

### ISSUE THREAD

**Issue by oksett** [hanks-zyh/HTextView#48]
Hi,
i started to use your library and i find this error with basic setup that you provided.

My layout is:

<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:htext="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="com.example.htextviewexample.MainActivity">

    <com.hanks.htextview.HTextView
        android:id="@+id/text"
        android:layout_width="match_parent"
        android:layout_height="100dp"
        android:background="#000000"
        android:gravity="center"
        android:textColor="#FFFFFF"
        android:textSize="30sp"
        htext:animateType="anvil"
        htext:fontAsset="fonts/font-name.ttf" />

</android.support.constraint.ConstraintLayout>

My gradle:
`apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"
    defaultConfig {
        applicationId "com.example.htextviewexample"
        minSdkVersion 15
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.2.0'
    compile 'com.android.support.constraint:constraint-layout:1.0.0-beta4'
    compile 'hanks.xyz:htextview-library:0.1.5'
    testCompile 'junit:junit:4.12'
}
`

And MainActivity:

`package com.example.htextviewexample;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

    }
}
`

The Exception is:
`FATAL EXCEPTION: main
                                                                            Process: com.example.htextviewexample, PID: 6243
                                                                            java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.htextviewexample/com.example.htextviewexample.MainActivity}: android.view.InflateException: Binary XML file line #9: Error inflating class com.hanks.htextview.HTextView`

**Comment by RABSHET0** [comment]
try this 
`<com.hanks.htextview.HTextView
        android:id="@+id/code"
        android:layout_width="368dp"
        android:layout_height="33dp"

        android:background="#000000"
        android:gravity="center"
        android:textColor="#FFFFFF"
        android:textSize="20sp"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintHorizontal_bias="0.0"
        app:layout_constraintTop_toBottomOf="@+id/code" />


    HTextView Code=(HTextView) view.findViewById(R.id.code);
        Code.setAnimateType(HTextViewType.RAINBOW);
        Code.animateText("Code:"); // animate
`
it work with me

**Comment by hanks-zyh** [comment]
have a try https://github.com/hanks-zyh/HTextView/commit/15ccfa93388e935e3f24ffe3cbadc7330427e6b6
