### ISSUE TITLE
Please set minimum api level to 14

### ISSUE THREAD

**Issue by NikhilAndroidDev** [hanks-zyh/HTextView#5]

**Comment by xu6148152** [comment]
You can use nineoldanimation to replace the current animator.

**Comment by hanks-zyh** [comment]
@NikhilAndroidDev i suggest that you can download the library and build it by change the `build.gradle` file

**Comment by NikhilAndroidDev** [comment]
@hanks-zyh  Ok let  me try

**Comment by NikhilAndroidDev** [comment]
@xu6148152  I heard that NineOldAndroid is depreciated . Any how Thank You
