### ISSUE TITLE
Issue with Typer

### ISSUE THREAD

**Issue by abh22ishek** [hanks-zyh/HTextView#59]
Typer Text view is not working

**Comment by appaaaa** [comment]
me too

**Comment by abh22ishek** [comment]
It looks like there is bug on typer textview

**Comment by hanks-zyh** [comment]
could you please some code and screenshot or some logs?

**Comment by abh22ishek** [comment]
i haven't got any error , it just simply displays normal text. 
Thats all!

**Comment by hanks-zyh** [comment]
use lastest version try again
