### ISSUE TITLE
Namespace htext is not bound

### ISSUE THREAD

**Issue by EnduroXPro** [hanks-zyh/HTextView#6]
When I add the xml to my layout file I get the issue namespace text is not bound. 
How can I solve that?

The xml:

  <com.hanks.htextview.HTextView
            android:id="@+id/htext"
            android:layout_width="match_parent"
            android:layout_height="100dp"
            android:background="#000000"
            android:gravity="center"
            android:textColor="#FFFFFF"
            android:textSize="30sp"
            htext:animateType="anvil"
            />

**Comment by EnduroXPro** [comment]
well, the solution was to add htext - prefix manually: 
xmlns:htext="http://schemas.android.com/apk/res-auto"

**Comment by hanks-zyh** [comment]
@EnduroXPro I'm sorry that i did not describe it in readme, thank you for your remind
