### ISSUE TITLE
not show well when set layout_width and layout_height wrap_content

### ISSUE THREAD

**Issue by JohnTsaiAndroid** [hanks-zyh/HTextView#9]
![image](https://cloud.githubusercontent.com/assets/8317477/12047053/1768b1b0-af00-11e5-8c01-05dafb1b187e.png)

**Comment by hanks-zyh** [comment]
@JohnTsaiAndroid  Sorry ,I didn't consider this situation, maybe I will support it on next version, if you can solve it, welcom to commit pr, i will appreciate it.
